// <auto-generated />
using System;
using DTO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DTO.Migrations
{
    [DbContext(typeof(MusicalStoreContext))]
    partial class MusicalStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DTO.Models.BinhLuan", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<DateOnly?>("NgayDang")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Sao")
                        .HasColumnType("int");

                    b.HasKey("MaKh", "MaSp")
                        .HasName("PK__BINH_LUA__F5579F9FC6E17241");

                    b.HasIndex("MaSp");

                    b.ToTable("BINH_LUAN", (string)null);
                });

            modelBuilder.Entity("DTO.Models.ChiTietGiamGia", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("MaGg")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaGG");

                    b.Property<DateOnly?>("NgayBd")
                        .HasColumnType("date")
                        .HasColumnName("NgayBD");

                    b.Property<DateOnly?>("NgayKt")
                        .HasColumnType("date")
                        .HasColumnName("NgayKT");

                    b.HasKey("MaSp", "MaGg")
                        .HasName("PK__CHI_TIET__155752F40C7EF9D8");

                    b.HasIndex("MaGg");

                    b.ToTable("CHI_TIET_GIAM_GIA", (string)null);
                });

            modelBuilder.Entity("DTO.Models.ChucVu", b =>
                {
                    b.Property<string>("MaCv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaCV");

                    b.Property<int?>("MucLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenCv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenCV");

                    b.HasKey("MaCv")
                        .HasName("PK__CHUC_VU__27258E763D8D5847");

                    b.ToTable("CHUC_VU", (string)null);
                });

            modelBuilder.Entity("DTO.Models.CtDonHang", b =>
                {
                    b.Property<string>("MaDh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaDH");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("MaDh", "SoLuong")
                        .HasName("PK__CT_DON_H__52737C6725ADE823");

                    b.ToTable("CT_DON_HANG", (string)null);
                });

            modelBuilder.Entity("DTO.Models.CtPhieuNhap", b =>
                {
                    b.Property<string>("MaPn")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaPN");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<double?>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<int?>("Slnhap")
                        .HasColumnType("int")
                        .HasColumnName("SLNhap");

                    b.HasKey("MaPn", "MaSp")
                        .HasName("PK__CT_PHIEU__F557B7712CD9316A");

                    b.HasIndex("MaSp");

                    b.ToTable("CT_PHIEU_NHAP", (string)null);
                });

            modelBuilder.Entity("DTO.Models.CtSanPham", b =>
                {
                    b.Property<string>("MaCtsp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCTSP");

                    b.Property<string>("GioiThieu")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongSo")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TinhNang")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCtsp")
                        .HasName("PK__CT_SAN_P__1E4FCECD0651B758");

                    b.ToTable("CT_SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("DTO.Models.DonHang", b =>
                {
                    b.Property<string>("MaDh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaDH");

                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaPttt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaPTTT");

                    b.Property<int?>("MaTt")
                        .HasColumnType("int")
                        .HasColumnName("MaTT");

                    b.Property<DateOnly>("NgayLap")
                        .HasColumnType("date");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TongTienHang")
                        .HasColumnType("float");

                    b.Property<double>("TongTt")
                        .HasColumnType("float")
                        .HasColumnName("TongTT");

                    b.HasKey("MaDh")
                        .HasName("PK__DON_HANG__2725866136FFA2BC");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaPttt");

                    b.HasIndex("MaTt");

                    b.ToTable("DON_HANG", (string)null);
                });

            modelBuilder.Entity("DTO.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("NgaySinhKh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinhKH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TenKH");

                    b.HasKey("MaKh")
                        .HasName("PK__KHACH_HA__2725CF1E1C748EF7");

                    b.ToTable("KHACH_HANG", (string)null);
                });

            modelBuilder.Entity("DTO.Models.LoaiSanPham", b =>
                {
                    b.Property<string>("MaLsp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaLSP");

                    b.Property<string>("TenLsp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenLSP");

                    b.HasKey("MaLsp")
                        .HasName("PK__LOAI_SAN__3B983FFE73DE8B14");

                    b.ToTable("LOAI_SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("DTO.Models.MaGiamGia", b =>
                {
                    b.Property<string>("MaGg")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaGG");

                    b.Property<string>("ChiTiet")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GiaTriGiam")
                        .HasColumnType("int");

                    b.HasKey("MaGg")
                        .HasName("PK__MA_GIAM___2725AE8263AD34E0");

                    b.ToTable("MA_GIAM_GIA", (string)null);
                });

            modelBuilder.Entity("DTO.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("TenNcc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc")
                        .HasName("PK__NHA_CUNG__3A185DEB0EC52CBD");

                    b.ToTable("NHA_CUNG_CAP", (string)null);
                });

            modelBuilder.Entity("DTO.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaCv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaCV");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TenNV");

                    b.HasKey("MaNv")
                        .HasName("PK__NHAN_VIE__2725D70A836C3D7B");

                    b.HasIndex("MaCv");

                    b.ToTable("NHAN_VIEN", (string)null);
                });

            modelBuilder.Entity("DTO.Models.PhanQuyen", b =>
                {
                    b.Property<string>("MaPq")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaPQ");

                    b.Property<string>("TenPq")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenPQ");

                    b.HasKey("MaPq")
                        .HasName("PK__PHAN_QUY__2725E7F37E0A52DF");

                    b.ToTable("PHAN_QUYEN", (string)null);
                });

            modelBuilder.Entity("DTO.Models.PhieuNhap", b =>
                {
                    b.Property<string>("MaPn")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaPN");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly?>("NgayLap")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayXuat")
                        .HasColumnType("date");

                    b.HasKey("MaPn")
                        .HasName("PK__PHIEU_NH__2725E7F0F32683B7");

                    b.HasIndex("MaNcc");

                    b.HasIndex("MaNv");

                    b.ToTable("PHIEU_NHAP", (string)null);
                });

            modelBuilder.Entity("DTO.Models.PtThanhToan", b =>
                {
                    b.Property<string>("MaPttt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaPTTT");

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NganHang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("SDT");

                    b.Property<string>("Stk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STK");

                    b.Property<string>("TenNhan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaPttt")
                        .HasName("PK__PT_THANH__B30A28028AF8FF85");

                    b.ToTable("PT_THANH_TOAN", (string)null);
                });

            modelBuilder.Entity("DTO.Models.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("Dvt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DVT");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("Hang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Hinh")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaCtGiamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCtGiamGiaNavigationMaGg")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaCtGiamGiaNavigationMaSp")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaCtsp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCTSP");

                    b.Property<string>("MaLsp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaLSP");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Slsp")
                        .HasColumnType("int")
                        .HasColumnName("SLSP");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SAN_PHAM__2725081C89E7C261");

                    b.HasIndex("MaCtsp");

                    b.HasIndex("MaLsp");

                    b.HasIndex("MaCtGiamGiaNavigationMaSp", "MaCtGiamGiaNavigationMaGg");

                    b.ToTable("SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("DTO.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTk")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaTK");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MaPq")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaPQ");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenTk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TenTK");

                    b.HasKey("MaTk")
                        .HasName("PK__TAI_KHOA__2725007095687E5D");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.HasIndex("MaPq");

                    b.ToTable("TAI_KHOAN", (string)null);
                });

            modelBuilder.Entity("DTO.Models.TinhTrang", b =>
                {
                    b.Property<int>("MaTt")
                        .HasColumnType("int")
                        .HasColumnName("MaTT");

                    b.Property<string>("TenTt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTT");

                    b.HasKey("MaTt")
                        .HasName("PK__TINH_TRA__272500792636AA7B");

                    b.ToTable("TINH_TRANG", (string)null);
                });

            modelBuilder.Entity("DTO.Models.BinhLuan", b =>
                {
                    b.HasOne("DTO.Models.KhachHang", "MaKhNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__BINH_LUAN__MaKH__5DCAEF64");

                    b.HasOne("DTO.Models.SanPham", "MaSpNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__BINH_LUAN__MaSP__5EBF139D");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("DTO.Models.ChiTietGiamGia", b =>
                {
                    b.HasOne("DTO.Models.MaGiamGia", "MaGgNavigation")
                        .WithMany("ChiTietGiamGia")
                        .HasForeignKey("MaGg")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_G__MaGG__5165187F");

                    b.HasOne("DTO.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietGiamGia")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_G__MaSP__5070F446");

                    b.Navigation("MaGgNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("DTO.Models.CtDonHang", b =>
                {
                    b.HasOne("DTO.Models.DonHang", "MaDhNavigation")
                        .WithMany("CtDonHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__CT_DON_HAN__MaDH__5AEE82B9");

                    b.Navigation("MaDhNavigation");
                });

            modelBuilder.Entity("DTO.Models.CtPhieuNhap", b =>
                {
                    b.HasOne("DTO.Models.PhieuNhap", "MaPnNavigation")
                        .WithMany("CtPhieuNhaps")
                        .HasForeignKey("MaPn")
                        .IsRequired()
                        .HasConstraintName("FK__CT_PHIEU_N__MaPN__6754599E");

                    b.HasOne("DTO.Models.SanPham", "MaSpNavigation")
                        .WithMany("CtPhieuNhaps")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__CT_PHIEU_N__MaSP__68487DD7");

                    b.Navigation("MaPnNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("DTO.Models.DonHang", b =>
                {
                    b.HasOne("DTO.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__DON_HANG__MaKH__5629CD9C");

                    b.HasOne("DTO.Models.PtThanhToan", "MaPtttNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaPttt")
                        .HasConstraintName("FK__DON_HANG__MaPTTT__5812160E");

                    b.HasOne("DTO.Models.TinhTrang", "MaTtNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaTt")
                        .HasConstraintName("FK__DON_HANG__MaTT__571DF1D5");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaPtttNavigation");

                    b.Navigation("MaTtNavigation");
                });

            modelBuilder.Entity("DTO.Models.NhanVien", b =>
                {
                    b.HasOne("DTO.Models.ChucVu", "MaCvNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaCv")
                        .HasConstraintName("FK__NHAN_VIEN__MaCV__3B75D760");

                    b.Navigation("MaCvNavigation");
                });

            modelBuilder.Entity("DTO.Models.PhieuNhap", b =>
                {
                    b.HasOne("DTO.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__PHIEU_NHA__MaNCC__6383C8BA");

                    b.HasOne("DTO.Models.NhanVien", "MaNvNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__PHIEU_NHAP__MaNV__6477ECF3");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("DTO.Models.SanPham", b =>
                {
                    b.HasOne("DTO.Models.CtSanPham", "MaCTSPNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaCtsp")
                        .HasConstraintName("FK__CT__SAN_PHAM__MaCTSP");

                    b.HasOne("DTO.Models.LoaiSanPham", "MaLspNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLsp")
                        .HasConstraintName("FK__SAN_PHAM__MaLSP__48CFD27E");

                    b.HasOne("DTO.Models.ChiTietGiamGia", "MaCtGiamGiaNavigation")
                        .WithMany()
                        .HasForeignKey("MaCtGiamGiaNavigationMaSp", "MaCtGiamGiaNavigationMaGg");

                    b.Navigation("MaCTSPNavigation");

                    b.Navigation("MaCtGiamGiaNavigation");

                    b.Navigation("MaLspNavigation");
                });

            modelBuilder.Entity("DTO.Models.TaiKhoan", b =>
                {
                    b.HasOne("DTO.Models.KhachHang", "MaKhNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__TAI_KHOAN__MaKH__403A8C7D");

                    b.HasOne("DTO.Models.NhanVien", "MaNvNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__TAI_KHOAN__MaNV__412EB0B6");

                    b.HasOne("DTO.Models.PhanQuyen", "MaPqNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaPq")
                        .HasConstraintName("FK__TAI_KHOAN__MaPQ__4222D4EF");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("MaPqNavigation");
                });

            modelBuilder.Entity("DTO.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DTO.Models.CtSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DTO.Models.DonHang", b =>
                {
                    b.Navigation("CtDonHangs");
                });

            modelBuilder.Entity("DTO.Models.KhachHang", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("DonHangs");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DTO.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DTO.Models.MaGiamGia", b =>
                {
                    b.Navigation("ChiTietGiamGia");
                });

            modelBuilder.Entity("DTO.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("DTO.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuNhaps");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DTO.Models.PhanQuyen", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DTO.Models.PhieuNhap", b =>
                {
                    b.Navigation("CtPhieuNhaps");
                });

            modelBuilder.Entity("DTO.Models.PtThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("DTO.Models.SanPham", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("ChiTietGiamGia");

                    b.Navigation("CtPhieuNhaps");
                });

            modelBuilder.Entity("DTO.Models.TinhTrang", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
